build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false

complexity:
  active: true
  CyclomaticComplexMethod:
    active: true
    ignoreSimpleWhenEntries: true
  LongMethod:
    active: true
    threshold: 120
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 7
    ignoreAnnotated:
      - 'Composable'
  TooManyFunctions:
    active: true
    thresholdInFiles: 15
    thresholdInClasses: 15

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: false

naming:
  active: true
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*|[A-Z][a-zA-Z0-9]*'
    excludeClassPattern: '.*Test'
  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'
  PackageNaming:
    active: true
    packagePattern: '[a-z]+(\.[a-z][A-Za-z0-9]*)*'
  MatchingDeclarationName:
    active: false

style:
  active: true
  MaxLineLength:
    active: true
    maxLineLength: 200
  MagicNumber:
    active: false
  ForbiddenComment:
    active: true
    comments:
      - 'FIXME:'
      - 'STOPSHIP:'
  UnusedPrivateMember:
    active: true
    ignoreAnnotated:
      - 'Preview'
      - 'PreviewLightDark'
  UnusedParameter:
    active: false

performance:
  active: true
  SpreadOperator:
    active: false

potential-bugs:
  active: true
